# ========================================
# NETLIFY CONFIGURATION - STETHOLINK AI
# ========================================
# Ultra-minimal configuration for guaranteed deployment

[build]
  publish = "public"

# SPA fallback for PWA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 